"""
Generates a realistic sample CSV so you can run the full pipeline immediately
without waiting for the scraper to finish.

Uses 30 real fragrances with accurate note profiles from public fragrance databases.
These are the most important pairings for validating your model.

Run:
    python generate_sample_data.py
    python build_index.py --raw data/raw/sample.csv
    streamlit run app.py
"""

import csv
from pathlib import Path

SAMPLE = [
    # ── Luxury ──────────────────────────────────────────────────────────────
    {
        "name": "Aventus",
        "brand": "Creed",
        "price_tier": "luxury",
        "url": "https://www.fragrantica.com/perfume/Creed/Aventus-810.html",
        "concentration": "EDP",
        "top_notes": "pineapple|bergamot|black currant|apple",
        "middle_notes": "birch|patchouli|moroccan jasmine|rose",
        "base_notes": "musk|oakmoss|ambergris|vanilla",
        "main_accords": "fresh fruity|woody|sweet|aromatic",
    },
    {
        "name": "Sauvage",
        "brand": "Dior",
        "price_tier": "luxury",
        "url": "https://www.fragrantica.com/perfume/Dior/Sauvage-28807.html",
        "concentration": "EDT",
        "top_notes": "bergamot|pepper",
        "middle_notes": "lavender|pink pepper|vetiver|patchouli|geranium|elemi resin|iso e super",
        "base_notes": "ambergris|cedar|labdanum",
        "main_accords": "aromatic|fresh spicy|woody|citrus",
    },
    {
        "name": "Baccarat Rouge 540",
        "brand": "Maison Francis Kurkdjian",
        "price_tier": "luxury",
        "url": "https://www.fragrantica.com/perfume/Maison-Francis-Kurkdjian/Baccarat-Rouge-540-29204.html",
        "concentration": "EDP",
        "top_notes": "jasmine|saffron",
        "middle_notes": "amberwood|ambrofix",
        "base_notes": "fir resin|cedar|musk",
        "main_accords": "sweet|warm spicy|woody|amber",
    },
    {
        "name": "Eros",
        "brand": "Versace",
        "price_tier": "luxury",
        "url": "https://www.fragrantica.com/perfume/Versace/Eros-17080.html",
        "concentration": "EDT",
        "top_notes": "mint|green apple|lemon",
        "middle_notes": "tonka bean|ambroxan|geranium",
        "base_notes": "vanilla|vetiver|oakmoss|cedarwood",
        "main_accords": "sweet|fresh|aromatic|woody",
    },
    {
        "name": "Bleu de Chanel",
        "brand": "Chanel",
        "price_tier": "luxury",
        "url": "https://www.fragrantica.com/perfume/Chanel/Bleu-de-Chanel-18920.html",
        "concentration": "EDP",
        "top_notes": "grapefruit|lemon|mint|pink pepper",
        "middle_notes": "ginger|iso e super|jasmine|nutmeg",
        "base_notes": "incense|vetiver|white musk|cedar|sandalwood",
        "main_accords": "aromatic|fresh|woody|citrus",
    },
    {
        "name": "Y",
        "brand": "Yves Saint Laurent",
        "price_tier": "luxury",
        "url": "https://www.fragrantica.com/perfume/Yves-Saint-Laurent/Y-49014.html",
        "concentration": "EDP",
        "top_notes": "bergamot|ginger|apple",
        "middle_notes": "sage|geranium|juniper",
        "base_notes": "ambergris|fir balsam|cedarwood|vetiver",
        "main_accords": "aromatic|fresh|woody|green",
    },
    {
        "name": "Acqua di Giò Profumo",
        "brand": "Giorgio Armani",
        "price_tier": "luxury",
        "url": "https://www.fragrantica.com/perfume/Giorgio-Armani/Acqua-di-Gio-Profumo-36469.html",
        "concentration": "EDP",
        "top_notes": "bergamot|sea notes|rosemary",
        "middle_notes": "lavender|geranium|sage|incense",
        "base_notes": "patchouli|sandalwood|labdanum|mineral notes",
        "main_accords": "aromatic|fresh|aquatic|woody",
    },
    {
        "name": "1 Million",
        "brand": "Paco Rabanne",
        "price_tier": "luxury",
        "url": "https://www.fragrantica.com/perfume/Paco-Rabanne/1-Million-12191.html",
        "concentration": "EDT",
        "top_notes": "blood mandarin|peppermint|grapefruit",
        "middle_notes": "rose|cinnamon|spices",
        "base_notes": "leather|amber|patchouli|white musk|blond wood",
        "main_accords": "warm spicy|sweet|leather|woody",
    },
    {
        "name": "Tobacco Vanille",
        "brand": "Tom Ford",
        "price_tier": "luxury",
        "url": "https://www.fragrantica.com/perfume/Tom-Ford/Tobacco-Vanille-30262.html",
        "concentration": "EDP",
        "top_notes": "tobacco leaf|spices",
        "middle_notes": "tobacco flower|jasmine|cacao|ginger",
        "base_notes": "vanilla|tonka bean|amber|musk",
        "main_accords": "warm spicy|sweet|tobacco|vanilla",
    },
    {
        "name": "Oud Wood",
        "brand": "Tom Ford",
        "price_tier": "luxury",
        "url": "https://www.fragrantica.com/perfume/Tom-Ford/Oud-Wood-8171.html",
        "concentration": "EDP",
        "top_notes": "rosewood|cardamom|Chinese pepper",
        "middle_notes": "oud|sandalwood|vetiver",
        "base_notes": "tonka bean|amber|musk",
        "main_accords": "woody|oud|warm spicy|sweet",
    },
    {
        "name": "Noir de Noir",
        "brand": "Tom Ford",
        "price_tier": "luxury",
        "url": "https://www.fragrantica.com/perfume/Tom-Ford/Noir-de-Noir-36059.html",
        "concentration": "EDP",
        "top_notes": "black pepper|saffron|bergamot",
        "middle_notes": "rose|jasmine|black truffle|oud",
        "base_notes": "vanilla|musk|patchouli|sandalwood",
        "main_accords": "floral|warm spicy|sweet|woody|oud",
    },
    {
        "name": "Replica Jazz Club",
        "brand": "Maison Margiela",
        "price_tier": "luxury",
        "url": "https://www.fragrantica.com/perfume/Maison-Margiela/Jazz-Club-32001.html",
        "concentration": "EDT",
        "top_notes": "lemon|neroli|pink pepper",
        "middle_notes": "tobacco leaf|vetiver|clary sage",
        "base_notes": "vanilla|musk|rum",
        "main_accords": "aromatic|tobacco|warm spicy|sweet",
    },
    {
        "name": "Amber Oud",
        "brand": "Al Haramain Perfumes",
        "price_tier": "affordable",
        "url": "https://www.fragrantica.com/perfume/Al-Haramain-Perfumes/Amber-Oud-49673.html",
        "concentration": "EDP",
        "top_notes": "mandarin orange|bergamot|saffron",
        "middle_notes": "oud|rose",
        "base_notes": "amber|musk|sandalwood",
        "main_accords": "sweet|warm spicy|oud|woody",
    },
    # ── Affordable ──────────────────────────────────────────────────────────
    {
        "name": "Club de Nuit Intense Man",
        "brand": "Armaf",
        "price_tier": "affordable",
        "url": "https://www.fragrantica.com/perfume/Armaf/Club-de-Nuit-Intense-Man-22818.html",
        "concentration": "EDT",
        "top_notes": "pineapple|bergamot|black currant|apple",
        "middle_notes": "jasmine|rose|birch",
        "base_notes": "musk|ambergris|patchouli|vanilla",
        "main_accords": "fresh fruity|woody|sweet|aromatic",
    },
    {
        "name": "Asad",
        "brand": "Lattafa Perfumes",
        "price_tier": "affordable",
        "url": "https://www.fragrantica.com/perfume/Lattafa-Perfumes/Asad-68091.html",
        "concentration": "EDP",
        "top_notes": "bergamot|pepper|grapefruit",
        "middle_notes": "lavender|geranium|ambroxan",
        "base_notes": "ambergris|musk|cedar|patchouli",
        "main_accords": "aromatic|fresh spicy|woody|citrus",
    },
    {
        "name": "Fakhar",
        "brand": "Lattafa Perfumes",
        "price_tier": "affordable",
        "url": "https://www.fragrantica.com/perfume/Lattafa-Perfumes/Fakhar-L-homme-87534.html",
        "concentration": "EDP",
        "top_notes": "jasmine|saffron|bergamot",
        "middle_notes": "amberwood|ambrofix|rose",
        "base_notes": "cedar|musk|sandalwood",
        "main_accords": "sweet|warm spicy|woody|amber",
    },
    {
        "name": "Dyson",
        "brand": "Armaf",
        "price_tier": "affordable",
        "url": "https://www.fragrantica.com/perfume/Armaf/Dyson-94301.html",
        "concentration": "EDP",
        "top_notes": "mint|green apple|lemon|bergamot",
        "middle_notes": "tonka bean|geranium|ambroxan",
        "base_notes": "vanilla|vetiver|oakmoss|cedarwood",
        "main_accords": "sweet|fresh|aromatic|woody",
    },
    {
        "name": "Blue Seduction",
        "brand": "Antonio Banderas",
        "price_tier": "affordable",
        "url": "https://www.fragrantica.com/perfume/Antonio-Banderas/Blue-Seduction-for-Men-1264.html",
        "concentration": "EDT",
        "top_notes": "melon|watermelon|mandarin orange",
        "middle_notes": "star anise|cardamom|lavender",
        "base_notes": "cedarwood|musk|amber",
        "main_accords": "fresh|aromatic|sweet|aquatic",
    },
    {
        "name": "Tobacco Oud",
        "brand": "Maison Alhambra",
        "price_tier": "affordable",
        "url": "https://www.fragrantica.com/perfume/Maison-Alhambra/Tobacco-Oud-92445.html",
        "concentration": "EDP",
        "top_notes": "tobacco leaf|saffron",
        "middle_notes": "oud|rose|jasmine",
        "base_notes": "vanilla|musk|amber|sandalwood",
        "main_accords": "warm spicy|sweet|tobacco|woody|oud",
    },
    {
        "name": "Heritage Oud",
        "brand": "Armaf",
        "price_tier": "affordable",
        "url": "https://www.fragrantica.com/perfume/Armaf/Heritage-Oud-94298.html",
        "concentration": "EDP",
        "top_notes": "cardamom|rosewood",
        "middle_notes": "oud|sandalwood|vetiver",
        "base_notes": "tonka bean|amber|musk",
        "main_accords": "woody|oud|warm spicy|sweet",
    },
    {
        "name": "Black Afgano",
        "brand": "Nasomatto",
        "price_tier": "luxury",
        "url": "https://www.fragrantica.com/perfume/Nasomatto/Black-Afgano-5697.html",
        "concentration": "Parfum",
        "top_notes": "coffee",
        "middle_notes": "oud|hashish",
        "base_notes": "resin|tobacco leaf|incense",
        "main_accords": "tobacco|smoky|oud|earthy",
    },
    {
        "name": "Café Firenze",
        "brand": "Maison Alhambra",
        "price_tier": "affordable",
        "url": "https://www.fragrantica.com/perfume/Maison-Alhambra/Cafe-Firenze-96002.html",
        "concentration": "EDP",
        "top_notes": "coffee|bergamot",
        "middle_notes": "oud|tobacco leaf|incense",
        "base_notes": "amber|musk|sandalwood",
        "main_accords": "tobacco|smoky|oud|sweet",
    },
    {
        "name": "Cool Water",
        "brand": "Davidoff",
        "price_tier": "affordable",
        "url": "https://www.fragrantica.com/perfume/Davidoff/Cool-Water-2773.html",
        "concentration": "EDT",
        "top_notes": "sea notes|neroli|rosemary|mint",
        "middle_notes": "lavender|jasmine|geranium",
        "base_notes": "musk|amber|oakmoss|cedarwood",
        "main_accords": "aquatic|fresh|aromatic|green",
    },
    {
        "name": "Light Blue",
        "brand": "Dolce & Gabbana",
        "price_tier": "luxury",
        "url": "https://www.fragrantica.com/perfume/Dolce-Gabbana/Light-Blue-1285.html",
        "concentration": "EDT",
        "top_notes": "grapefruit|sea notes|cedar",
        "middle_notes": "apple|jasmine|bluebell|bamboo",
        "base_notes": "musk|amber|cedarwood",
        "main_accords": "fresh|aquatic|citrus|floral",
    },
    {
        "name": "Cool Off",
        "brand": "Armaf",
        "price_tier": "affordable",
        "url": "https://www.fragrantica.com/perfume/Armaf/Cool-Off-Man-90056.html",
        "concentration": "EDT",
        "top_notes": "sea notes|bergamot|grapefruit",
        "middle_notes": "jasmine|apple|bamboo",
        "base_notes": "musk|amber|cedar",
        "main_accords": "fresh|aquatic|citrus|floral",
    },
    {
        "name": "Invictus",
        "brand": "Paco Rabanne",
        "price_tier": "luxury",
        "url": "https://www.fragrantica.com/perfume/Paco-Rabanne/Invictus-21154.html",
        "concentration": "EDT",
        "top_notes": "grapefruit|sea notes|mandarin orange",
        "middle_notes": "bay leaf|jasmine|hedione",
        "base_notes": "guaiac wood|oakmoss|ambergris",
        "main_accords": "fresh|woody|citrus|aromatic",
    },
    {
        "name": "Pegasus",
        "brand": "Parfums de Marly",
        "price_tier": "luxury",
        "url": "https://www.fragrantica.com/perfume/Parfums-de-Marly/Pegasus-23259.html",
        "concentration": "EDP",
        "top_notes": "bergamot|lavender|heliotrope",
        "middle_notes": "jasmine|geranium|sandalwood",
        "base_notes": "vanilla|musk|ambergris|tonka bean",
        "main_accords": "sweet|powdery|aromatic|woody|floral",
    },
    {
        "name": "Whisper",
        "brand": "Armaf",
        "price_tier": "affordable",
        "url": "https://www.fragrantica.com/perfume/Armaf/Whisper-90055.html",
        "concentration": "EDP",
        "top_notes": "bergamot|lavender|heliotrope",
        "middle_notes": "jasmine|geranium|sandalwood",
        "base_notes": "vanilla|musk|ambergris|tonka bean",
        "main_accords": "sweet|powdery|aromatic|floral",
    },
    {
        "name": "Rose Anonyme",
        "brand": "By Kilian",
        "price_tier": "luxury",
        "url": "https://www.fragrantica.com/perfume/By-Kilian/Rose-Anonyme-32210.html",
        "concentration": "EDP",
        "top_notes": "mandarin orange|bergamot|cardamom",
        "middle_notes": "rose|jasmine|incense",
        "base_notes": "oud|sandalwood|patchouli|musk",
        "main_accords": "floral|oud|warm spicy|sweet",
    },
    {
        "name": "Khamrah",
        "brand": "Lattafa Perfumes",
        "price_tier": "affordable",
        "url": "https://www.fragrantica.com/perfume/Lattafa-Perfumes/Khamrah-95421.html",
        "concentration": "EDP",
        "top_notes": "cardamom|cinnamon|saffron",
        "middle_notes": "rose|oud|jasmine",
        "base_notes": "vanilla|musk|ambergris|sandalwood",
        "main_accords": "sweet|warm spicy|oud|vanilla|floral",
    },
]

FIELDS = [
    "name", "brand", "price_tier", "url",
    "concentration", "top_notes", "middle_notes", "base_notes", "main_accords",
]


def main():
    out = Path("data/raw/sample.csv")
    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=FIELDS)
        writer.writeheader()
        writer.writerows(SAMPLE)
    print(f"Wrote {len(SAMPLE)} fragrances to {out}")
    print("Now run: python build_index.py --raw data/raw/sample.csv")


if __name__ == "__main__":
    main()
